### PR TITLE
Modification des valeurs par defaut des Enum

### LINKED ISSUE #816: Fatal errors when creating models
Hello,

The following commands make R crash, instead of just printing an error message.

```{r}

library(gstlearn)

model=Model_create(ECov_fromKey("TOTO")) 
## je pense que le pbm vient du fait que ECov_fromKey a quand meme retourné un pointeur

model=Model_createFromParam(ECov_fromKeys(c("NUGGET","EXPONENTIAL")))

```

### PR DESCRIPTION
**Pull request by drenard77810**
Robustification of Enum.
Currently (this is a draft), when using a non valid key for Enum, the mechanism uses the default key. The modification consists in turning the default key to a choice among the VALID keys (in particular not UNKNOWN).
Therefore all the default keys have been adapted.
This draft is there to check that this change does not provoke any regression along the tests.

Fix #816

### CODE REVIEW

File: include/Enum/EConsElem.hpp [hunk 1]
```diff
@@ -12,16 +12,16 @@
...
-                       ANGLE,    2, "Anisotropy rotation angle (degree)", \
-                       PARAM,    3, "Auxiliary parameter", \
-                       SILL,     4, "Sill", \
-                       SCALE,    5, "Scale", \
-                       T_RANGE,  6, "Tapering range", \
-                       VELOCITY, 7, "Velocity (advection)", \
-                       SPHEROT,  8, "Rotation angle for Sphere", \
-                       TENSOR,   9, "Anisotropy Matrix term"
+#define ENUM_CONS_ELEM EConsElem, UNDEFINED,                           \
+                       UNDEFINED, 0, "Unknown constraint",             \
```
Comment (fabien-ors) [inline include/Enum/EConsElem.hpp]: Does UNDEFINED EConsElem really make sense? To be deleted?

File: include/Enum/ECalcVario.hpp [hunk 2]
```diff
@@ -16,7 +16,7 @@
 /**
  * TODO : Documentation
  */
-#define ENUM_CALC_VARIO ECalcVario, UNDEFINED,                                           \
+#define ENUM_CALC_VARIO ECalcVario, VARIOGRAM,                                           \
                         UNDEFINED, -1, "Undefined",                                      \
```
Comment (fabien-ors) [inline include/Enum/ECalcVario.hpp]: Does UNDEFINED ECalcVario really make sense? To be deleted?

File: include/Enum/EAnam.hpp [hunk 3]
```diff
@@ -12,12 +12,12 @@
...
 
-#define ENUM_ANAM EAnam, HERMITIAN, \
-                  UNKNOWN,     0,  "Undefined", \
-                  EXTERNAL,    1,  "External anamorphosis", \
-                  HERMITIAN,   2,  "Hermitian anamorphosis", \
-                  EMPIRICAL,   3,  "Empirical anamorphosis", \
-                  DISCRETE_DD, 4,  "Disjunctive Discrete anamorphosis", \
-                  DISCRETE_IR, 5,  "Indicator Residuals anamorphosis"
+#define ENUM_ANAM EAnam, UNDEFINED,                                    \
+                  UNDEFINED, 0, "Undefined",                           \
```
Comment (fabien-ors) [inline include/Enum/EAnam.hpp]: Does UNDEFINED EAnam really make sense? To be deleted?

File: include/Enum/ECov.hpp [hunk 4]
```diff
@@ -12,7 +12,7 @@
 
 #include "Enum/AEnum.hpp"
 
-#define ENUM_COV ECov, UNKNOWN,\
+#define ENUM_COV ECov, NUGGET,\
                  UNKNOWN,    -2, "Unknown covariance",\
```
Comment (fabien-ors) [inline include/Enum/ECov.hpp]: Remove UNKNOWN ?

**Review by fabien-ors — APPROVED** [review]
UNDEFINED keywords should be deleted when non relevant (in a future work)
